[app]
name = ""

[message_queue]
url = ""

[auth_credentials_storage]
base_url = ""
http_client_timeout = 60

[dodo_is]
country_code = ""
http_client_timeout = 60

[sentry]
is_enabled = false
dsn = ""
traces_sample_rate = 1.0
profiles_sample_rate = 1.0
